/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2018-12-31 12:08:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.buss;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class student_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/ssms/apache-tomcat-8.5.37/webapps/ScoreManager/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1523600116000L));
    _jspx_dependants.put("jar:file:/D:/ssms/apache-tomcat-8.5.37/webapps/ScoreManager/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt-1_0-rt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/pages/system/base.jsp", Long.valueOf(1523600116000L));
    _jspx_dependants.put("jar:file:/D:/ssms/apache-tomcat-8.5.37/webapps/ScoreManager/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plug-in/easyui-1.4.1/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plug-in/easyui-1.4.1/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"plug-in/jquery/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plug-in/easyui-1.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plug-in/easyui-1.4.1/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plug-in/easyui-1.4.1/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/system/validform.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/system/curdtools.js\"></script>\r\n");
      out.write("<!--  \r\n");
      out.write("<script type=\"text/javascript\" src=\"js/system/forbiddenutil.js\"></script>\r\n");
      out.write("-->");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>学生</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"dg\" class=\"\" title=\"列表\" style=\"width: 700px; height: 300px\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'ck',checkbox:true\"></th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'studentnum',width:80\">学号</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'name',width:80\">学生姓名</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'sex',width:80\" formatter=\"changeValue\">性别</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'birthday',width:80\" formatter=\"changeDate\">出生日期</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'qq',width:80\">qq</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'mobile',width:80\">电话</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"toolbar\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton add\" iconCls=\"icon-add\" onclick=\"create()\" plain=\"true\">新增</a> \r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton edit\" iconCls=\"icon-edit\" onclick=\"edit()\" plain=\"true\">修改</a> \r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton remove\" iconCls=\"icon-remove\" onclick=\"del()\" plain=\"true\">删除</a>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t学号: <input class=\"easyui-textbox\" id=\"paramStudentnum\">\r\n");
      out.write("\t\t\t学生姓名: <input class=\"easyui-textbox\" id=\"paramStudent\">\r\n");
      out.write("\t\t\t电话: <input class=\"easyui-textbox\" id=\"paramMobile\">\r\n");
      out.write("\t\t\tqq: <input class=\"easyui-textbox\" id=\"paramQq\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" onclick=\"studentSearch()\" iconCls=\"icon-search\">查找</a>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" onclick=\"studentReset()\" iconCls=\"icon-search\">清空</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dlg\" class=\"easyui-dialog\" title=\"数据参数\" data-options=\"modal:true\" style=\"width: 480px; height: 430px;\" closed=\"true\" buttons=\"#dlg-buttons\">\r\n");
      out.write("\t\t<form method=\"post\" id=\"fm\">\r\n");
      out.write("\t\t\t<table cellpadding=\"5\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"hidden\" id=\"id\" name=\"id\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>学号:</td>\r\n");
      out.write("\t    \t\t\t<td><input class=\"easyui-textbox\" id=\"studentnum\" type=\"text\" name=\"studentnum\" validtype=\"checkNum\" maxlength=\"15\" required=\"true\" missingMessage=\"学号必须填写\"></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>学生姓名:</td>\r\n");
      out.write("\t    \t\t\t<td><input class=\"easyui-textbox\" id=\"name\" type=\"text\" name=\"name\" maxlength=\"10\" required=\"true\" missingMessage=\"姓名必须填写\"></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>性别:</td>\r\n");
      out.write("\t    \t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"sex\" id=\"sex\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\" selected=\"selected\">男</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">女</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>出生日期:</td>\r\n");
      out.write("\t    \t\t\t<td><input class=\"easyui-datebox\" id=\"birthday\" editable=\"false\" maxlength=\"20\" type=\"text\" name=\"birthday\"></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>qq:</td>\r\n");
      out.write("\t    \t\t\t<td><input class=\"easyui-textbox\" id=\"qq\" validtype=\"qq\" maxlength=\"15\" type=\"text\" name=\"qq\" ></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>电话:</td>\r\n");
      out.write("\t    \t\t\t<td><input class=\"easyui-textbox\" id=\"mobile\" type=\"text\" name=\"mobile\" validtype=\"mobile\" ></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dlg-update\" class=\"easyui-dialog\" title=\"数据参数\" data-options=\"modal:true\" style=\"width: 480px; height: 430px;\" closed=\"true\" buttons=\"#update-buttons\">\r\n");
      out.write("\t\t<form method=\"post\" id=\"fm-update\">\r\n");
      out.write("\t\t\t<table cellpadding=\"5\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"hidden\" id=\"id\" name=\"id\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>学号:</td>\r\n");
      out.write("\t    \t\t\t<td><input class=\"easyui-textbox\" id=\"studentnum\" type=\"text\" name=\"studentnum\" readonly=\"readonly\" maxlength=\"20\" ></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>学生姓名:</td>\r\n");
      out.write("\t    \t\t\t<td><input class=\"easyui-textbox\" id=\"name\" type=\"text\" name=\"name\" maxlength=\"10\" required=\"true\" missingMessage=\"姓名必须填写\"></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>性别:</td>\r\n");
      out.write("\t    \t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"sex\" id=\"sex\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\" selected=\"selected\">男</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">女</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>出生日期:</td>\r\n");
      out.write("\t    \t\t\t<td><input class=\"easyui-datebox\" id=\"birthday\" editable=\"false\" maxlength=\"20\" type=\"text\" name=\"birthday\"></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>qq:</td>\r\n");
      out.write("\t    \t\t\t<td><input class=\"easyui-textbox\" id=\"qq\" validtype=\"qq\" maxlength=\"15\" type=\"text\" name=\"qq\" ></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>电话:</td>\r\n");
      out.write("\t    \t\t\t<td><input class=\"easyui-textbox\" id=\"mobile\" type=\"text\" name=\"mobile\" validtype=\"mobile\" ></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"update-buttons\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton  save\" onclick=\"update()\" iconCls=\"icon-ok\">保存</a> \r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton cancel\" onclick=\"javascript:$('#dlg-update').dialog('close')\" iconCls=\"icon-cancel\">取消</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dlg-buttons\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton  save\" onclick=\"save()\" iconCls=\"icon-ok\">保存</a> \r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton cancel\" onclick=\"javascript:$('#dlg').dialog('close')\" iconCls=\"icon-cancel\">取消</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {  \r\n");
      out.write("\t\tloadDataGrid();\r\n");
      out.write("    });  \t\r\n");
      out.write("\tfunction studentSearch(){\r\n");
      out.write("\t\tvar queryCondition = {'studentnum':$('#paramStudentnum').val(),'name':$('#paramStudent').val(),'mobile': $('#paramMobile').val(),'qq': $('#paramQq').val(),'dormName': $('#paramDormName').val()};\r\n");
      out.write("\t\tloadDataGrid(queryCondition);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction studentReset(){\r\n");
      out.write("\t\t$('#paramStudentnum').textbox('setValue','');\r\n");
      out.write("\t\t$('#paramStudent').textbox('setValue','');\r\n");
      out.write("\t\t$('#paramMobile').textbox('setValue','');\r\n");
      out.write("\t\t$('#paramQq').textbox('setValue','');\r\n");
      out.write("\t\t$('#paramDormName').textbox('setValue','');\r\n");
      out.write("\t\tloadDataGrid(null);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction openWin(dgrid,dtittle){\r\n");
      out.write("\t\t$('#'+dgrid).dialog('open').dialog('setTitle',dtittle);\r\n");
      out.write("\t\tloadClassGrid();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction loadDataGrid(queryConditon){\r\n");
      out.write("\t\t $('#dg').datagrid({  \r\n");
      out.write("\t            title : '学生信息',  \r\n");
      out.write("\t            iconCls : 'icon-ok',  \r\n");
      out.write("\t            pageSize : 5,//默认选择的分页是每页5行数据  \r\n");
      out.write("\t            pageList : [ 5, 10, 15, 20 ],//可以选择的分页集合  \r\n");
      out.write("\t            nowrap : true,//设置为true，当数据长度超出列宽时将会自动截取  \r\n");
      out.write("\t            striped : true,//设置为true将交替显示行背景。  \r\n");
      out.write("\t            collapsible : true,//显示可折叠按钮  \r\n");
      out.write("\t            toolbar:\"#toolbar\",//在添加 增添、删除、修改操作的按钮要用到这个  \r\n");
      out.write("\t            url:'studentController.do?datagrid',//url调用Action方法  \r\n");
      out.write("\t            loadMsg : '数据装载中......',  \r\n");
      out.write("\t            singleSelect:false,//为true时只能选择单行  \r\n");
      out.write("\t            fitColumns:true,//允许表格自动缩放，以适应父容器  \r\n");
      out.write("\t            checkOnSelect:true,\r\n");
      out.write("\t            selectOnCheck:true,\r\n");
      out.write("\t            fit:true,\r\n");
      out.write("\t            remoteSort : false,  \r\n");
      out.write("\t            pagination : true,  \r\n");
      out.write("\t            rownumbers : true,\r\n");
      out.write("\t            queryParams:queryConditon\r\n");
      out.write("\t        });   \r\n");
      out.write("\t}\r\n");
      out.write("    function changeValue(value, row, index){\r\n");
      out.write("        if (value == \"1\") {\r\n");
      out.write("            return '男';\r\n");
      out.write("        }\r\n");
      out.write("        else {\r\n");
      out.write("            return '女';\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\t\tvar url;\r\n");
      out.write("\t\tfunction create(){\r\n");
      out.write("\t\t\t$('#dlg').dialog('open').dialog('setTitle','新建');\r\n");
      out.write("\t\t\t$('#fm').form('clear');\r\n");
      out.write("\t\t\turl = 'studentController.do?save';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction edit(){\r\n");
      out.write("\t\t\tvar row = $('#dg').datagrid('getSelections');\r\n");
      out.write("\t\t\tif (row.length == 1){\r\n");
      out.write("\t\t\t\t$('#dlg-update').dialog('open').dialog('setTitle','编辑');\r\n");
      out.write("\t\t\t\t$('#fm-update').form('clear');\r\n");
      out.write("\t\t\t\t$('#fm-update').form('load',row[0]);\r\n");
      out.write("\t\t\t\turl = 'studentController.do?update';\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\ttitle: '提示信息',\r\n");
      out.write("\t\t\t\t\tmsg: '请选择一行数据再进行编辑！'\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction save(){\r\n");
      out.write("\t\t\t$('#fm').form('submit',{\r\n");
      out.write("\t\t\t\turl: url,\r\n");
      out.write("\t\t\t\tonSubmit: function(){\r\n");
      out.write("\t\t\t\t\treturn $(this).form('validate');\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess: function(result){\r\n");
      out.write("\t\t\t\t\tvar result = eval('('+result+')');\r\n");
      out.write("\t\t\t\t\tif (result.success){\r\n");
      out.write("\t\t\t\t\t\t$('#dlg').dialog('close');\t\t\r\n");
      out.write("\t\t\t\t\t\t$('#dg').datagrid('reload');\t\r\n");
      out.write("\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\ttitle: '提示信息',\r\n");
      out.write("\t\t\t\t\t\t\tmsg: result.msg\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\ttitle: '提示信息',\r\n");
      out.write("\t\t\t\t\t\t\tmsg: result.msg\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction update(){\r\n");
      out.write("\t\t\t$('#fm-update').form('submit',{\r\n");
      out.write("\t\t\t\turl: url,\r\n");
      out.write("\t\t\t\tonSubmit: function(){\r\n");
      out.write("\t\t\t\t\treturn $(this).form('validate');\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess: function(result){\r\n");
      out.write("\t\t\t\t\tvar result = eval('('+result+')');\r\n");
      out.write("\t\t\t\t\tif (result.success){\r\n");
      out.write("\t\t\t\t\t\t$('#dlg-update').dialog('close');\t\t\r\n");
      out.write("\t\t\t\t\t\t$('#dg').datagrid('reload');\t\r\n");
      out.write("\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\ttitle: '提示信息',\r\n");
      out.write("\t\t\t\t\t\t\tmsg: result.msg\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\ttitle: '提示信息',\r\n");
      out.write("\t\t\t\t\t\t\tmsg: result.msg\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction del(){\r\n");
      out.write("\t\t\tvar rows = $('#dg').datagrid('getSelections');\r\n");
      out.write("\t\t\tvar ids = [];\r\n");
      out.write("\t\t\tif (rows.length > 0){\r\n");
      out.write("\t\t\t\t$.messager.confirm('提示信息','确定删除?',function(r){\r\n");
      out.write("\t\t\t\t\tif (r){\r\n");
      out.write("\t\t\t\t\t\tfor ( var i = 0; i < rows.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\tids.push(rows[i].id);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl : 'studentController.do?delete',\r\n");
      out.write("\t\t\t\t\t\t\ttype : 'post',\r\n");
      out.write("\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\tids : ids.join(',')\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tcache : false,\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t\t\tif (result.success){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#dg').datagrid('reload');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$.messager.show({\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle: '提示信息',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmsg: result.msg\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$.messager.show({\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle: '提示信息',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmsg: result.msg\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$.messager.show({\t\r\n");
      out.write("\t\t\t\t\ttitle: '提示信息',\r\n");
      out.write("\t\t\t\t\tmsg: '请至少选择一条数据后再进行删除'\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
